parser: babel-eslint

plugins:
  - flowtype

extends:
  - airbnb
  - plugin:prettier/recommended

env:
  node: true
  browser: true

rules:

  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      useTabs: false
      semi: true
      singleQuote: true
      trailingComma: all
      bracketSpacing: true
      jsxBracketSameLine: true
      arrowParens: avoid
      rangeStart: 0
      requirePragma: false
      insertPragma: false
      proseWrap: preserve

  eqeqeq: [error, smart]
  no-dupe-keys: error
  no-return-assign: off
  consistent-return: off
  no-console: off

  import/prefer-default-export: off
  import/no-extraneous-dependencies: off

  react/jsx-filename-extension: [error, { extensions: [.js] }]
  react/jsx-one-expression-per-line: off

  flowtype/define-flow-type: error
  flowtype/no-dupe-keys: error
  flowtype/no-mutable-array: error
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/require-valid-file-annotation: [error, never, { annotationStyle: block }]
  flowtype/type-id-match: [error, '^[A-Z][a-z0-9]*']
  flowtype/use-flow-type: error
