sudo: required

language: node_js

node_js:
  - '10'

services:
  - docker

before_script:
  - yarn

jobs:
  include:
    - stage: Tests
      script:
        - cd examples/react-project/back && yarn
        - cd ../front && yarn
        - cd ../../..
        - yarn lint
        - yarn flow
