sudo: required

language: node_js

node_js:
  - '10'

services:
  - docker

before_script:
  - yarn

jobs:
  include:
    - stage: Tests
      script:
        - yarn lint
        - yarn flow

    - stage: Publish
      if: tag =~ ^v
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        - export NAME=$(jl package.json name)
        - export MAJOR=$(./version.js major)
        - export MINOR=$(./version.js minor)
        - export PATCH=$(./version.js patch)

        - docker build -t "$NAME:latest" -t "$NAME:$PATCH" -t "$NAME:$MINOR" -t "$NAME:$MAJOR" .

        - docker tag "$NAME:latest" "$NAMESPACE/$NAME:latest"
        - docker tag "$NAME:$PATCH" "$NAMESPACE/$NAME:$PATCH"
        - docker tag "$NAME:$MINOR" "$NAMESPACE/$NAME:$MINOR"
        - docker tag "$NAME:$MAJOR" "$NAMESPACE/$NAME:$MAJOR"

        - docker push "$NAMESPACE/$NAME:latest"
        - docker push "$NAMESPACE/$NAME:$PATCH"
        - docker push "$NAMESPACE/$NAME:$MINOR"
        - docker push "$NAMESPACE/$NAME:$MAJOR"
