sudo: required

language: node_js

node_js:
  - '10'

services:
  - docker

jobs:
  include:
    - stage: Tests
      script:
        - yarn
        - yarn --cwd examples/react-project/back
        - yarn --cwd examples/react-project/front
        - yarn lint
        - yarn flow
    - stage: Build image
      script:
        - docker build .
    - stage: Build examples
      script:
        - docker build examples/react-project/back
        - docker build examples/react-project/front
